# Generated by Django 5.0.2 on 2024-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_rename_empid_employeedetail_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
