# Generated by Django 5.0.2 on 2024-03-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0004_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
