# Generated by Django 5.0.2 on 2024-03-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0005_employeeexperience_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperience',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='salary',
        ),
    ]
