# Generated by Django 5.0.2 on 2024-03-06 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0006_remove_employeeexperience_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp1_designation',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp1_duration',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp1_name',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp1_salary',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp2_designation',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp2_duration',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp2_name',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp2_salary',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp3_designation',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp3_duration',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp3_name',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='cmp3_salary',
        ),
        migrations.CreateModel(
            name='EmploymentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='experiences',
            field=models.ManyToManyField(to='employeeApp.employmentexperience'),
        ),
    ]
