# Generated by Django 5.0.2 on 2024-03-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0007_remove_employeeexperience_cmp1_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('passing_year', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='college_hsc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='college_pg',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='college_ssc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='college_ug',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='course_hsc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='course_pg',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='course_ssc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='course_ug',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='passing_year_hsc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='passing_year_pg',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='passing_year_ssc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='passing_year_ug',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='percentage_hsc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='percentage_pg',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='percentage_ssc',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='percentage_ug',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='hsc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsc_education', to='employeeApp.education'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='pg',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pg_education', to='employeeApp.education'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='ssc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssc_education', to='employeeApp.education'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='ug',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ug_education', to='employeeApp.education'),
        ),
    ]
