# Generated by Django 5.0.2 on 2024-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0008_education_remove_employeeeducation_college_hsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentexperience',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmentexperience',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmentexperience',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmentexperience',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
