# Generated by Django 5.0.2 on 2024-03-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0009_alter_employmentexperience_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='experiences',
            new_name='experience',
        ),
    ]
