# Generated by Django 5.0.2 on 2024-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0011_alter_employeeeducation_hsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='education',
            field=models.ManyToManyField(to='employeeApp.education'),
        ),
    ]
